// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtBOGZzpJwuz3pxRL1aGoM66qpH508ExE',
    appId: '1:782530892930:web:e137b6ba52d82975d5909b',
    messagingSenderId: '782530892930',
    projectId: 'lifetime-558ae',
    authDomain: 'lifetime-558ae.firebaseapp.com',
    storageBucket: 'lifetime-558ae.firebasestorage.app',
    measurementId: 'G-NP4G6DK70C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXdPa8sZ5Lnkx6apJYFT5m8aYDSqrdsLc',
    appId: '1:782530892930:android:ff8d3168dc432efdd5909b',
    messagingSenderId: '782530892930',
    projectId: 'lifetime-558ae',
    storageBucket: 'lifetime-558ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5N_ILehDLb_J4aEL1v0VVe17-0WXVNys',
    appId: '1:782530892930:ios:8750b6c3d831bc09d5909b',
    messagingSenderId: '782530892930',
    projectId: 'lifetime-558ae',
    storageBucket: 'lifetime-558ae.firebasestorage.app',
    iosBundleId: 'com.example.lifeTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5N_ILehDLb_J4aEL1v0VVe17-0WXVNys',
    appId: '1:782530892930:ios:8750b6c3d831bc09d5909b',
    messagingSenderId: '782530892930',
    projectId: 'lifetime-558ae',
    storageBucket: 'lifetime-558ae.firebasestorage.app',
    iosBundleId: 'com.example.lifeTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtBOGZzpJwuz3pxRL1aGoM66qpH508ExE',
    appId: '1:782530892930:web:daefc66f08738142d5909b',
    messagingSenderId: '782530892930',
    projectId: 'lifetime-558ae',
    authDomain: 'lifetime-558ae.firebaseapp.com',
    storageBucket: 'lifetime-558ae.firebasestorage.app',
    measurementId: 'G-8PLYC56ST3',
  );
}
